name: 0.0$(Rev:.r)

variables:
  SYSTEM_DEBUG: true

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Scripts
    pool:
      vmImage: ubuntu-latest
    steps:

    # Install the necessary packages in order to compile the scripts
    - task: Npm@1
      displayName: Install NPM Module
      inputs:
        verbose: $(System.Debug)

    # Perform a linting test on the typescript files
    - task: Npm@1
      displayName: Lint Typescript Files
      inputs:
        command: custom
        customCommand: run lint
        verbose: $(System.Debug)

    # Compile (transpile) and package the module
    - task: Npm@1
      displayName: Compile Typescript Files
      inputs:
        command: custom
        customCommand: run build
        verbose: $(System.Debug)

    # Create an archive of the dist directory
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
        includeRootFolder: false
        archiveType: 'tar'
        archiveFile: '$(Build.ArtifactStagingDirectory)/arm-template-deploy-$(Build.BuildNumber).tar.gz'
        replaceExistingArchive: true

    # Publish the artifacts
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: $(Build.ArtifactsStagingDirectory)
        ArtifactName: build

- stage: Deploy
  displayName: GitHub Release
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Release to GitHub
    pool:
      vmImage: ubuntu-latest
    environment: GitHub
    strategy:
      runOnce:
        deploy:
          steps:
            - task: GitHubRelease@0
              inputs:
                gitHubConnnection: ARM-Template-Deploy-Repo
                repository: $(Build.Repository.Name)
                action: create
                target: $(Build.SourceVersion)
                tagSource: auto
                tag: $(Build.BuildNumber)
